# Utilisez l'image de base Node.js
FROM node:19

# Définit le répertoire de travail à l'intérieur du conteneur
WORKDIR /app

# Copie package.json et package-lock.json pour installer les dépendances
COPY package*.json ./

# Installe les dépendances
RUN npm install

# Copie le reste des fichiers de l'application
COPY . .

# Expose le port 3000 pour accéder à l'application React
EXPOSE 3000

# Commande de démarrage pour lancer l'application React
CMD ["npm", "start"]
